checkpoint_path: train_root_dir/Transformer_Diffusion/checkpoint/12-27-12AM-16-05/epoch=2323-loss=0.01832.ckpt

OPTION: 1

eval_output_path: log/ours/

t5_max_sentence_length: 512

evaluation:
  sdf_model_path: train_root_dir/SDF/checkpoint/09-03-08PM-58-07/sdf_epoch=0679-loss=0.00300.ckpt

gensdf_latentcode_evaluator:
  gensdf_model_path: null
  resolution: 16
  max_batch: 262144         # 2 ^ 18

number_of_trial: 20
